### ISSUE TITLE
Unable to communicate with/via signaling server

### ISSUE THREAD

**Issue by iripiri** [VILLASframework/signaling#9]
When trying to connect with either the JavaScript or the VILLASnode client, the connection is not working as expected.

In the webclient (https://villas.fein-aachen.org/webrtc/), the initial connection works, but when trying to send a message, the datachannel is null:
![grafik](https://github.com/VILLASframework/signaling/assets/34569601/ad95f732-4278-495d-ac3e-2dfc41ab68d2)

Error description for VILLASnode test will follow in the comments.

**Comment by al3xa23** [comment]
Hi, 

here the error I get when using the villas node webRTC client using the same setup as in the webclient. 

![image](https://github.com/VILLASframework/signaling/assets/140614263/af7d96de-0e45-4ac5-a985-1b02f74e17a1)

**Comment by pjungkamp** [comment]
There seems to be a protocol error on the signaling server side. The first client connects and receives a proper control message from the server. The second one fails to establish the websocket connection because of an incorrect HTTP response while trying to upgrade the HTTPS connection to a websocket connection.

The upgrade of a connection from HTTP to Websocket should return a 101 code on success. But our signaling server sends a 200 code to the second websocket client.

**Comment by pjungkamp** [comment]
I'll have to take some wireshark captures to see what the signaling server is actually sending there...

**Comment by stv0g** [comment]
I only see the following in the log of the signaling server:

```
2023/10/09 10:11:57 ERROR Failed to read session=KUCHEN peer=d6ff4940-4891-05ac-39e0-54a1e5dd196e remote=10.42.182.64:40750 error="websocket: close 1006 (abnormal closure): unexpected EOF"
```

I am going to continue investigating here..

**Comment by stv0g** [comment]
Hi @PJungkamp @al3xa23 @iripiri,

I've made some progress and found the root issue of the problem.

Our error reporting in the signaling was pretty broken. But this has been now resolved in: https://github.com/VILLASframework/signaling/pull/11

The error was caused by reusing the same peer ID in both VILLASnode instances.
To fully understand the implications, I will need to elaborate a bit:

VILLASnode's WebRTC node-type uses the concept of a _session ID_ to connect two peers.
Each peer must use the same session ID to find its remote peer.
In that sense the session is much like an Zoom session URL/ID and should probably also be treated confidential as everybody in possession of the session ID could connect to your VILLASnode instance.

In addition to the session IDs, we also introduced the concept of _peer IDs_.
Peer IDs must be unique in each session. Like the session ID, they are arbitrary strings and can be choosen by the user.

Like the session ID is configured by the `session` setting, the peer ID is configured by `peer`.
If no peer ID is configured, we will automatically derive one from the nodes name.

And here we ran into issues: because you likely used the same configuration file for both peers, and no explicity configured peer ID, you have started both VILLASnode instances with the same peer ID.
This is forbidden by the signaling server and the server should return an error (which it didnt).

Do solve this:
- create two configuration files. One for each VILLASnode instance
- use unique names for the `webrtc` node or specify the `peer` setting for them

I am still thinking about how we could solve this better.
Its a pitfall which we should try to avoid by default.
E.g. by randomly assigning a peer ID or maybe requiring the user to define one explicity.

**Comment by al3xa23** [comment]
Hi, 

here a quick summary how you can let it work: 
If you communicate with the signaling server instance in kuberenetes: use two configuration files, with unique names for your webrtc node. Use `server ="https://villas.k8s.eonerc.rwth-aachen.de/ws/signaling"`
If you communicate with signaling server in a simple docker container: `server = "wss://127.0.0.1:8080/ws/signaling"`
